name: PR to Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.7
          
      - name: Terraform Init
        run: terraform init
          
      - name: Terraform Plan
        run: terraform plan -no-color